name: al_quran
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  bitsdojo_window: ^0.1.6
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.3
  flutter_isolate: ^2.1.0
  provider: ^6.1.2
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_remix: ^0.0.3
  get_it: ^8.0.2
  dio: ^5.7.0
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  easy_localization: ^3.0.7
  proste_indexed_stack: ^0.2.4
  flutter_svg: ^2.0.14
  flutter_html: ^3.0.0-beta.2
  mask_text_input_formatter: ^2.9.0
  scrollable_positioned_list: ^0.3.8
  indexed_list_view: ^4.0.0
  url_launcher: ^6.3.1
  sms_autofill: ^2.4.1
  syncfusion_flutter_pdfviewer: ^27.2.4
  webview_flutter: ^4.10.0
  app_links: ^6.3.2
  flutter_widget_from_html: ^0.15.3
  flutter_markdown: ^0.7.4+3
  webview_windows: ^0.4.0
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview_windows: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.14.1




flutter_icons:
  mac: true
  windows:
    generate: true
    image_path: "assets/png/al_logo.png"
    icon_size: 48
  image_path: 'assets/png/al_logo.png'

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/tr/
    - assets/

